# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x11getavailablepears\"\x1d\n\x0fIPAddressClient\x12\n\n\x02ip\x18\x01 \x01(\t\"\x18\n\nIPResponse\x12\n\n\x02ip\x18\x01 \x01(\t2a\n\x11GetAvailablePears\x12L\n\x05\x41\x64\x64IP\x12\".getavailablepears.IPAddressClient\x1a\x1d.getavailablepears.IPResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IPADDRESSCLIENT']._serialized_start=36
  _globals['_IPADDRESSCLIENT']._serialized_end=65
  _globals['_IPRESPONSE']._serialized_start=67
  _globals['_IPRESPONSE']._serialized_end=91
  _globals['_GETAVAILABLEPEARS']._serialized_start=93
  _globals['_GETAVAILABLEPEARS']._serialized_end=190
# @@protoc_insertion_point(module_scope)
